### PR TITLE
Add Web Component ADR

### PR DESCRIPTION
**Pull request by heymatthenry**
This PR just creates a new `decisions` directory in this repo where we can add architectural/product decision records, as well as adding an ADR for the decision to use web components going forward (many more ADRs to come in the near to medium term).

### CODE REVIEW

**Comment by annepetersen** [comment]
So I was about to edit this to capitalize Web Components consistently, because I'd been told it acts as a kind of brand that way and can be confusing otherwise. I've been pointed to the [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) to support that point, but once I checked that source, they even do it inconsistently. 

Not to hold up this PR, but can we make a call about which will be the case for us? cc @sarah-sch and @finekatie

**Comment by sarah-sch** [comment]
> So I was about to edit this to capitalize Web Components consistently, because I'd been told it acts as a kind of brand that way and can be confusing otherwise. I've been pointed to the [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) to support that point, but once I checked that source, they even do it inconsistently.
> 
> Not to hold up this PR, but can we make a call about which will be the case for us? cc @sarah-sch and @finekatie

@annepetersen and @finekatie - My gut reaction is that we should capitalize because maybe lowercase "web components" could refer to something more like USWDS's current component collection (or one from another design system). Capital "Web Components" = the new technology we're adapting. Maybe eventually as this technology evolves and becomes commonplace we (and others) will shift towards lowercase, but for now I think capitalization might be helpful. Especially because I see it capitalized in other sources such as W3C and Wikipedia. 

Totally open to other takes here. It's not a straightforward call, and I know we try to use caps somewhat sparingly.

**Comment by finekatie** [comment]
> > So I was about to edit this to capitalize Web Components consistently, because I'd been told it acts as a kind of brand that way and can be confusing otherwise. I've been pointed to the [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) to support that point, but once I checked that source, they even do it inconsistently.
> > Not to hold up this PR, but can we make a call about which will be the case for us? cc @sarah-sch and @finekatie
> 
> @annepetersen and @finekatie - My gut reaction is that we should capitalize because maybe lowercase "web components" could refer to something more like USWDS's current component collection (or one from another design system). Capital "Web Components" = the new technology we're adapting. Maybe eventually as this technology evolves and becomes commonplace we (and others) will shift towards lowercase, but for now I think capitalization might be helpful. Especially because I see it capitalized in other sources such as W3C and Wikipedia.
> 
> Totally open to other takes here. It's not a straightforward call, and I know we try to use caps somewhat sparingly.

I agree with Sarah on this. I think it requires capitalization for now to differentiate it from other instances where we refer to "components".

**Comment by annepetersen** [comment]
@heymatthenry and @thisisdano — still want to hear your input here, but given concurrence between the content strategists and I at least, I'll draft revisions

**Comment by heymatthenry** [comment]
I _love_ this discussion. I have a weak preference for lowercase because "web components" is just a colloquial descriptor for a specific technology ("HTML Custom Elements"). Beyond that, I only have a strong preference for consistency, so I'm happy with whatever looks like the consensus position.

**Comment by annepetersen** [comment]
Noting here for the record we had a discussion in Engineering sync that mostly supported capitalization for now

**Pull request merged**
